---
# This playbook contains common plays that will be run on the bastion node.

# Enable RHM repo & install templates
- name: Enable Red Hat Mobile repos
  shell: subscription-manager repos --enable="{{ rhmap_repo }}"
  become: yes

- name: Install templates & playbooks on bastion
  yum:  
    name: "rhmap-fh-openshift-templates"
    state: latest
  environment:
    http_proxy: "{{ proxy_url | default('') }}"
    https_proxy: "{{ proxy_url | default('') }}"
  become: yes

# Prepare RHMAP inventory file
- name: Setup ansible inventory for RHMAP
  template:
    src: rhmap_hosts.j2
    dest: /etc/ansible/hosts_rhmap
    mode: 0640
  become: yes

- name: Setup ansible variables for RHMAP CORE
  template:
    src: deploy-core-main.j2
    dest: /opt/rhmap/{{ rhmap_version }}/rhmap-installer/roles/deploy-core/defaults/main.yml
    mode: 0640
  become: yes

- name: Setup ansible variables for RHMAP MBAAS
  template:
    src: deploy-mbaas-main.j2
    dest: /opt/rhmap/{{ rhmap_version }}/rhmap-installer/roles/deploy-mbaas/defaults/main.yml
    mode: 0640
  become: yes

- name: "Install python-docker-py via yum"
  yum:
    name: python-docker-py
    enablerepo: rhel-7-server-extras-rpms
    state: present
  environment:
    http_proxy: "{{ proxy_url | default('') }}"
    https_proxy: "{{ proxy_url | default('') }}"
  become: yes
  when: ansible_os_family == 'RedHat'