---
# This playbook contains common plays that will be run on the bastion node.

# Deploy MBaaS
- name: Deploy Red Hat Mobile MBaaS
  shell: 'ANSIBLE_ROLES_PATH=/opt/rhmap/{{ rhmap_version}}/rhmap-installer/roles/ ansible-playbook -i /etc/ansible/hosts_rhmap 
  /opt/rhmap/{{ rhmap_version }}/rhmap-installer/playbooks/1-node-mbaas.yml -e "strict_mode=false" --skip-tags "label" > /tmp/rhmap-deploy-mbaas.out 2>&1'
  async: 5400
  poll: 30
  register: install_mbaas
  become: yes

- fail: msg="Failed to install RHMAP Core. Check log output /tmp/rhmap-deploy-mbaas.out"
  when: install_mbaas.rc is undefined or install_mbaas.rc != 0
