---
# This playbook deploys RHMAP

- name: prepare infrastructure (all nodes)
  hosts: all
  remote_user: root

  roles:
    - prepare-nodes

- name: prepare infrastructure (bastion node)
  hosts: bastion
  remote_user: root

  roles:
    - prepare-bastion

- name: prepare infrastructure PVs (bastion node)
  hosts: bastion
  remote_user: root

  roles:
    - prepare-pvs

- name: seed images core and mbaas (bastion node)
  hosts: bastion
  remote_user: root

  roles:
    - seed-images

- name: prepare core nodes (core node)
  hosts: bastion
  remote_user: root

  roles:
    - prepare-core-nodes

- name: prepare mbaas nodes (core mbaas)
  hosts: bastion
  remote_user: root

  roles:
    - prepare-mbaas-nodes

- name: check PVs infrastructure (bastion node)
  hosts: bastion

  roles:
    - check-pvs

- name: deploy RHMAP (bastion node)
  hosts: bastion
  remote_user: root

  roles:
    - deploy-core
    - deploy-mbaas

- name: Create RHMAP environments, dev, test, etc. (bastion node)
  hosts: bastion
  remote_user: root

  roles:
    - create-environments


