---
# This playbook contains common plays that will be run on the bastion node.

# Create PVs
- name: OCP login with user/pass
  shell: oc login {{ login_url }} --username={{ oc_user }} --password={{ oc_password }} --insecure-skip-tls-verify
  register: login_out
  become: yes
  when: oc_oauth_token is not defined

- name: OCP login with token
  shell: oc login {{ login_url }} --token={{ oc_oauth_token }} --insecure-skip-tls-verify
  register: login_out
  become: yes
  when: oc_oauth_token is defined

- name: Get OpenShift token
  shell: oc whoami -t
  register: ocp_whoami_token

- name: Debug info before ./create-pv.sh
  debug:
    msg: "./create-pv.sh {{ login_url }} {{ ocp_whoami_token.stdout }} {{ hostvars[groups['nfs'][0]]['ansible_default_ipv4']['address'] }} <item.name> <item.size>"

- script: ./create-pv.sh {{ login_url }} {{ ocp_whoami_token.stdout }} {{ hostvars[groups['nfs'][0]]['ansible_default_ipv4']['address'] }} {{ rhm_nfs_dir }} {{ item.name }} {{ item.size }}
  register: script_result
  failed_when: "script_result.rc != 0 and 'AlreadyExists' not in script_result.stdout"
  with_items: "{{ pvs }}"