---
# This playbook contains common plays that will be run on the bastion node.

# Create /srv/nfs/rhm/${PV_NAME}
- name: Create PVs
  file:
    path: /srv/nfs/rhm/{{ item.name }}
    owner: nfsnobody
    group: nfsnobody
    mode: 0644
    state: directory
  become: yes
  with_items: "{{ pvs }}"

# Example from Ansible Playbooks
- script: ./create-pv.sh hostvars['nfs'][0] {{ item.name }} {{ item.size }}
  with_items: "{{ pvs }}"