---
# This playbook contains common plays that will be run on all nodes.

- debug: var=rhn_username
- debug: var=rhn_pool_ids

- name: Subscribe nodes
  redhat_subscription:
    state: present
    username: "{{ rhn_username }}"
    password: "{{ rhn_password }}"
    pool_ids: "{{ rhn_pool_ids }}"
    autosubscribe: true
  register: subs_status
  become: yes
  #when: subs_status | bool == false

- debug: var=subs_status

# Refresh certificates
- name: Refresh certificates
  shell: subscription-manager refresh
  become: yes